name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend: Python API
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run backend unit tests
        working-directory: api
        run: pytest -v || true

      # Frontend: React SPA
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint and build frontend
        working-directory: frontend
        run: |
          npm run lint
          npm run build

      # Security Scanning
      - name: Run Gitleaks for secret scanning
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-banner --redact

      # Terraform Validation
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Validate Terraform files
        working-directory: infra
        run: |
          terraform fmt -check
          terraform validate

