name: Deploy Infrastructure and App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      KEYVAULT_NAME: ${{ secrets.KEYVAULT_NAME }}
      SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: infra
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve tfplan

      - name: Deploy API to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: clue-sip-web
          package: ./api

      - name: Deploy Frontend to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: frontend
          skip_app_build: false
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

      - name: Confirm Deployment URLs
        run: |
          echo "App Service URL: https://clue-sip-web.azurewebsites.net"
          echo "Static Web App URL: https://blue-pebble-08e9d7a03.2.azurestaticapps.net"
