name: Infrastructure

on:
  push:
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Plan
        working-directory: ./infra
        run: |
          terraform init -reconfigure
          terraform plan -out=tfplan

      - name: Terraform Apply (on main only)
        if: github.ref == 'refs/heads/main'
        working-directory: ./infra
        run: terraform apply -auto-approve tfplan
